### ISSUE TITLE
Save filter scene

### ISSUE THREAD

**Issue by LRahlff** [Mission-DMX/Project-Editor#55]
save a scene in filter mode needs a file already exist on the OS.
(was before also in direct mode, that have been changed already)

**Comment by Doralitze** [comment]
Furthermore we should unify the various file types into a single show file format. If we need changes to the XSD in order to do so, we should discuss this soon.

**Comment by Doralitze** [comment]
The bug meantioned by @LRahlff has already been fixed with commit [5bdab1d](https://github.com/Mission-DMX/Project-Editor/pull/68/commits/5bdab1debad338064cf53ddb2331175e1240540e). The issue about the fragmented file formats remains though.
