### ISSUE TITLE
Bug: Universe Node Settings issue

### ISSUE THREAD

**Issue by LRahlff** [Mission-DMX/Project-Editor#58]
Editing the universe node (patching of inputs to channels?) do some strange things:
(remembered: the list is unchanged, except another mapping is added with the last value, but it is not available in the UI (seen if i saved the scene))

First universe node has the id 0, which doesnt seem to match the first patch universe. (of by one)

**Comment by Doralitze** [comment]
See also the changes required by issue #48.

**Comment by Doralitze** [comment]
@LRahlff Could you please test/show me the first part of the issue using the show-browser-widget branch again? I cannot reproduce / do not understand the issue.

**Comment by LRahlff** [comment]
The name of additional inputs have an internal name: <bound method Terminal.name of <Terminal Universe.0.input_2>> : GRBW
Once i have visited the settings, additional inputs are not available in the settings.
It seems that only the last changed channel is saved, so only one channel can get changed (but the old one is also available: "13": "input_3 : GRBW","2": "input_3",).
In the left side: right klick and release does delete the scene.
