### ISSUE TITLE
Improve Error Diagnostics

### ISSUE THREAD

**Issue by Doralitze** [Mission-DMX/Project-Editor#78]
First of all, fish should Prefix the error log messages with individual error codes that are documented in the Docs repo and set the last occurred error to "Show File successfully loaded" after a show file has been loaded.

After doing so, the editor should scan the debug output for these error codes and should display a dialog, highlighting the corresponding lines from the log. It could also be a good idea if these error codes would be appended by a machine readable tag, describing the scene and filter ID in case of an error with a filter.

Furthermore, the editor should provide a tree or list for show file scheduling log in such a manner that the user can select to only review the log of the process that he's actually interested in. Folding for Scenes or errors would also be a good idea.

Last but not least, there should be a tab in that window that sends a `request_dmx_data` IPC message on a regular basis (for example once per second if the window is currently open) and parses the incoming `dmx_output` message in order to display the current DMX output (in a style similar to the patching view, where the channel of a fixture and its value are immediately visible.).

**Comment by Doralitze** [comment]
Alternatively, the current DMX output could also be displayed inside the patching view.

**Comment by Doralitze** [comment]
As the addition of virtual filters enhances complexity of XML generation we might as well think about implementing a debug view that displays the show configuration that was actually transmitted to fish.

**Comment by maxkaussow** [comment]
noch nicht ganz fertig
